# Generated by Django 5.0.3 on 2025-08-04 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('scanned_count', models.IntegerField(default=0)),
                ('first_scan_time', models.DateTimeField(blank=True, null=True)),
                ('last_scan_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateField()),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('scanned_count', models.IntegerField(default=0)),
                ('first_scan_time', models.DateTimeField(blank=True, null=True)),
                ('last_scan_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
